# -----------------------------------------------------------------------------
# Main manuscript table: standardised risk differences and relative risks
#
# Reads the enhanced core-condition summaries generated by
# 19_refresh_core3_risk_cis.R and produces a compact Word table focused on
# absolute (percentage-point) and relative effects.
#
# Output:
#   03_Output/tables/table_core3_risk_differences.docx
# -----------------------------------------------------------------------------

required_packages <- c("officer", "flextable")
missing_packages <- required_packages[!vapply(
  required_packages, requireNamespace, logical(1), quietly = TRUE
)]
if (length(missing_packages) > 0) {
  stop(
    "Missing required package(s): ", paste(missing_packages, collapse = ", "),
    ". Install them before running this script."
  )
}

suppressPackageStartupMessages({
  library(officer)
  library(flextable)
})

# ---- 1. Inputs and editable text --------------------------------------------

hosp_input <- file.path("01_Data", "core3_rr_hosp.RData")
death_input <- file.path("01_Data", "core3_rr_death.RData")
output_dir <- file.path("03_Output", "tables")
output_file <- file.path(output_dir, "table_core3_risk_differences.docx")

column_labels <- c(
  outcome = "Outcome",
  condition = "Condition",
  risk_difference = "Standardised risk difference,\npercentage points (95% CI)",
  rr_ci = "Standardised RR\n(95% CI)"
)

table_note <- paste0(
  "Risk difference is the standardised predicted risk with the focal condition ",
  "present minus that with the condition absent; positive values indicate higher ",
  "risk with the condition present. Models include diabetes, hypertension, and ",
  "chronic kidney disease simultaneously and adjust for age, sex, year, and ",
  "state of residence. Risk-difference and RR 95% CIs use the same paired ",
  "2,000-draw parametric bootstrap."
)

font_family <- "Arial"
condition_order <- c("Diabetes", "Hypertension", "Chronic kidney disease")

# ---- 2. Read and validate enhanced cached summaries -------------------------

if (!file.exists(hosp_input) || !file.exists(death_input)) {
  stop("Missing cached model summaries. Run 02_Script/19_refresh_core3_risk_cis.R first.")
}

load(hosp_input)   # creates core3_rr_hosp
load(death_input)  # creates core3_rr_death

required_columns <- c(
  "condition", "rr", "rr_lower", "rr_upper",
  "standardised_risk_difference",
  "standardised_risk_difference_lower",
  "standardised_risk_difference_upper"
)
for (object_name in c("core3_rr_hosp", "core3_rr_death")) {
  if (!exists(object_name, inherits = FALSE)) {
    stop("Expected object not found after loading input: ", object_name)
  }
  missing_columns <- setdiff(required_columns, names(get(object_name)))
  if (length(missing_columns) > 0) {
    stop(
      object_name, " lacks risk-difference CI columns. Run ",
      "02_Script/19_refresh_core3_risk_cis.R first. Missing: ",
      paste(missing_columns, collapse = ", ")
    )
  }
}

# ---- 3. Format the concise effect estimates ---------------------------------

format_risk_difference_ci <- function(estimate, lower, upper) {
  # Convert probabilities to percentage points. A leading sign on each value
  # makes the contrast direction immediately interpretable.
  sprintf("%+.2f (%+.2f to %+.2f)", 100 * estimate, 100 * lower, 100 * upper)
}

format_rr_ci <- function(rr, lower, upper) {
  sprintf("%.2f (%.2f-%.2f)", rr, lower, upper)
}

make_outcome_rows <- function(summary_table, outcome_label) {
  summary_table <- as.data.frame(summary_table)
  summary_table <- summary_table[match(condition_order, summary_table$condition), ]
  if (anyNA(summary_table$condition)) {
    stop("One or more expected core conditions are absent from: ", outcome_label)
  }

  data.frame(
    outcome = rep(outcome_label, 3),
    condition = summary_table$condition,
    risk_difference = format_risk_difference_ci(
      summary_table$standardised_risk_difference,
      summary_table$standardised_risk_difference_lower,
      summary_table$standardised_risk_difference_upper
    ),
    rr_ci = format_rr_ci(summary_table$rr, summary_table$rr_lower, summary_table$rr_upper),
    stringsAsFactors = FALSE
  )
}

main_table <- rbind(
  make_outcome_rows(core3_rr_hosp, "Hospitalisation"),
  make_outcome_rows(core3_rr_death, "Death from chikungunya")
)

# ---- 4. Construct the Word table --------------------------------------------

ft <- flextable(main_table)
ft <- set_header_labels(
  ft,
  outcome = column_labels[["outcome"]],
  condition = column_labels[["condition"]],
  risk_difference = column_labels[["risk_difference"]],
  rr_ci = column_labels[["rr_ci"]]
)
ft <- merge_v(ft, j = "outcome", part = "body")
ft <- valign(ft, j = "outcome", valign = "center", part = "body")

ft <- border_remove(ft)
thin_rule <- fp_border(color = "#C9D1D5", width = 0.65)
header_rule <- fp_border(color = "#7E8A90", width = 1.0)
ft <- hline_top(ft, part = "header", border = header_rule)
ft <- hline_bottom(ft, part = "header", border = header_rule)
ft <- hline(ft, i = seq_len(nrow(main_table)), part = "body", border = thin_rule)
ft <- bg(ft, part = "header", bg = "#EEF1F3")
ft <- color(ft, part = "all", color = "#263238")
ft <- font(ft, part = "all", fontname = font_family)
ft <- fontsize(ft, part = "header", size = 8.5)
ft <- fontsize(ft, part = "body", size = 8.25)
ft <- bold(ft, part = "header", bold = TRUE)
ft <- bold(ft, j = c("outcome", "condition"), part = "body", bold = TRUE)
ft <- align(ft, j = c("outcome", "risk_difference", "rr_ci"),
            align = "center", part = "all")
ft <- align(ft, j = "condition", align = "left", part = "all")
ft <- valign(ft, part = "all", valign = "center")
ft <- padding(ft, part = "all", padding.top = 4, padding.bottom = 4,
              padding.left = 5, padding.right = 5)
ft <- height(ft, part = "header", height = 0.52)
ft <- height(ft, part = "body", height = 0.34)
ft <- width(ft, j = "outcome", width = 1.00)
ft <- width(ft, j = "condition", width = 1.40)
ft <- width(ft, j = "risk_difference", width = 2.75)
ft <- width(ft, j = "rr_ci", width = 1.65)
ft <- set_table_properties(
  ft, layout = "fixed",
  opts_word = list(split = FALSE, keep_with_next = TRUE)
)

# ---- 5. Write Word document --------------------------------------------------

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
doc <- read_docx()
doc <- body_set_default_section(
  doc,
  value = prop_section(
    page_margins = page_mar(top = 0.65, bottom = 0.65, left = 0.55, right = 0.55)
  )
)
doc <- body_add_fpar(
  doc,
  value = fpar(
    ftext("Table X. ", prop = fp_text(font.family = font_family, bold = TRUE, font.size = 10)),
    ftext(
      "Standardised risk differences and relative risks by core underlying condition",
      prop = fp_text(font.family = font_family, font.size = 10)
    )
  )
)
doc <- body_add_par(doc, value = "", style = "Normal")
doc <- body_add_flextable(doc, value = ft, align = "center")
doc <- body_add_par(doc, value = "", style = "Normal")
doc <- body_add_fpar(
  doc,
  value = fpar(
    ftext("Note. ", prop = fp_text(font.family = font_family, italic = TRUE, font.size = 8)),
    ftext(table_note, prop = fp_text(font.family = font_family, font.size = 8))
  )
)

print(doc, target = output_file)

message("Risk-difference table written to: ", output_file)
print(main_table, row.names = FALSE)

